### ISSUE TITLE
Target running away from missed mouse clicks

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/seeme#13]
Is this a go-er?

**Comment by nebogeo** [comment]
This is now happening, it speeds up X2 for a short random period after you miss it... let me know what you think.

**Comment by scienceanna** [comment]
Sorry, slow response on this! Laura & I have been chatting about this and we think that while cool, having it speed up after one mouse click will probably make it a bit difficult for us to interpret the data. However, we both think that the targets could actually travel a bit faster right from the beginning - which should make it a bit harder. I was wondering if a missed click could also trigger a direction change, to give the player a feeling that the target is "responding" to them, but without changing the overall gameplay too much?

**Comment by nebogeo** [comment]
I've no set the speed to be halfway between the previous normal speed and the panic speed. Also removed panic and got it to change direction instead.
