### ISSUE TITLE
Game doesn't load on Firefox

### ISSUE THREAD

**Issue by lauraakelley** [nebogeo/seeme#15]
Loading page gets stuck at 98%, this is from before the new backgrounds were added.

**Comment by nebogeo** [comment]
That's odd, I'm testing it on firefox first...  - try holding down shift when you reload...

**Comment by lauraakelley** [comment]
No to worry, it must be something odd about my Firefox - it works on other people's here too. It's up to date, caches etc cleared and shift-reload doesn't work, so no idea what's going on there.

**Comment by nebogeo** [comment]
If it's still happening, try menu -> developer -> web console and paste what it says here...

**Comment by lauraakelley** [comment]
Still happening...

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-1.9.1.min.js:1:0
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] all.js
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. seeme.borrowed-scenery.com
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ ditto.js:558:0
not well-formed syntax.jscm:1:1
not well-formed base.jscm:1:1
"loading "scm/maths.jscm"" ditto.js:473:9
not well-formed egglab.jscm:1:1
"loading "scm/random.jscm"" ditto.js:473:9
not well-formed maths.jscm:1:1
"loading "scm/nightjar.jscm"" ditto.js:473:9
not well-formed random.jscm:1:1
"loading "scm/egglab-common.jscm"" ditto.js:473:9
not well-formed nightjar.jscm:1:1
not well-formed egglab-common.jscm:1:1
"error loading:facebook.png" ditto.js line 596 > eval:6:8
"error loading:twitter.png" ditto.js line 596 > eval:6:8

**Comment by nebogeo** [comment]
ok - I've removed the loading for those images (they were there so it's strange, but they are not needed), let me know if that fixes anything...

**Comment by lauraakelley** [comment]
Fixed, thanks!
