### ISSUE TITLE
Register domain, set up server properly.

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/seeme#19]
Choices choices:

dazzlebug.info 
dazzlebug.org
dazzle-bug.com 
dazzle-bug.co.uk
dazzle-bug.uk
dazzlegame.org
dazzlegame.info

**Comment by scienceanna** [comment]
We like dazzle-bug, and .com or .co.uk - either is fine :)

**Comment by nebogeo** [comment]
dazzle-bug.co.uk it is! (works now)
