### ISSUE TITLE
Patterning of targets

### ISSUE THREAD

**Issue by scienceanna** [nebogeo/seeme#3]
Would it be possible to have some more geometric patterns in the starter populations? At the moment the patterns seem quite diffuse/speckled - we're interested in the effects of stripes/spots/zigzags etc. and it's not clear to us how long it would take for these to evolve/whether they can evolve at all in the current parameter space.

**Comment by nebogeo** [comment]
No they can't in the current parameter space, but I'm dying to add them :)

**Comment by scienceanna** [comment]
Cool, please do!

**Comment by nebogeo** [comment]
This is now done - here are some examples of mutations of random genomes, we've added to the egglab parameter space so all the previous patterns can still be expressed too...

![4](https://cloud.githubusercontent.com/assets/5367/8019123/aaa1be26-0c36-11e5-8481-83108a06f5ea.png)
![3](https://cloud.githubusercontent.com/assets/5367/8019133/ce3172be-0c36-11e5-9e8d-a2bc719d9de3.png)
![2](https://cloud.githubusercontent.com/assets/5367/8019136/d4959982-0c36-11e5-8c3a-20b6f0f62137.png)

**Comment by nebogeo** [comment]
Also - I've removed a feature we used in egglab that we decided was a mistake to include, where the same genome would create different variations of a pattern. The reasoning was to simulate environment interaction "noise" to avoid image recognition to specific patterns by the players. 

However this didn't really turn out to be an issue and it's quite a lot of added complexity to explain. Now the same genome will always provide exactly the same pattern - I'm assuming this is what you need...
