### ISSUE TITLE
Target trajectory & speed

### ISSUE THREAD

**Issue by scienceanna** [nebogeo/seeme#5]
It would be really good to have small (a couple of degrees) random changes in trajectory every few seconds to make the game more challenging.

With regards to target speed – it looks like the speeds are randomly chosen at the moment (?), but we think speed might have quite an important effect on capture difficulty (and might interact with pattern difficulty) - so we would like to keep the speed within a population consistent if possible. We could potentially have nine populations: 3 fast, 3 medium and 3 slow, but then this may mean we need an unachievable number of players, do you have any thoughts? Otherwise 6 populations of two different speeds may be a more realistic target. Having said this, it would also be quite good if participants can still see a mix of target speeds on any given game (so sampling from all the populations on each game) - is that possible with the current set up  or would that be too complicated?

**Comment by nebogeo** [comment]
ah I like the sound of that... yes to constant speed.

I'll break the population stuff into a separate issue I think...

**Comment by nebogeo** [comment]
Constant speed & changes of direction done...
