### ISSUE TITLE
Collection of data on click distance

### ISSUE THREAD

**Issue by scienceanna** [nebogeo/seeme#6]
Is it possible to collect data on the location of clicks (both misses and hits) in relation to the location of the target?

 Also how close does the click need to be to the target to register as a hit – we both felt like we were catching targets when the cursor wasn’t quite over the target.

**Comment by nebogeo** [comment]
yes I think position of both are being recorded, but I'll have to check now it's moving... might just be the start pos. 

I'll check the collision detection, I might be expanding it with the rotation...

**Comment by scienceanna** [comment]
Brilliant, thanks - if the position for the target can be the centre that would be really useful for analysis :)

**Comment by nebogeo** [comment]
Just looked into this in more detail - the way the patterns work is that they record how many times they have been tested by players and the total cumulative time it took to find them (which we divide to get the average time = fitness for selection). The concept is that a pattern may be tested many times with a specific set of image and the only thing that matters is how long it took people to find it.

We are not currently recording all mouse clicks, or positions of the patterns as this wasn't considered to be important but it would be possible to add this if you think you can get useful data from it - perhaps it'll be clearer if I show you the output data...

**Comment by scienceanna** [comment]
Having a look at some output data would be really helpful, thanks!

I think we probably can get useful data from the number of mouse clicks/position of the target. When the task is just detection, I agree it's not important as once the target has been found the actual clicking stage should be fairly easy. However, once moving, detection becomes much more straightforward,  but aiming accurately is more tricky. Longer RT should fairly directly correlate with accuracy, but it would be interesting for us to know how wrong people are aiming if they miss (and where their attempts were) and whether there's any variability in strategy e.g. do people wait a long time and then make one accurate attempt? Or do they just click immediately a lot until they get it?

**Comment by nebogeo** [comment]
Ahah I see, yes - shall we have a table in the database for attempts, or clicks - which records:

player id, pattern id, mouse pos x,y , pattern pos x,y, pattern direction x,y, success 0/1

positions will be in screen space, so you can subtract (and use euclid :) get the distance...

**Comment by nebogeo** [comment]
I also wonder if player accuracy needs to be in the simulation fitness function - as you say, single longer more accurate click may be better than loads that worked faster....

**Comment by nebogeo** [comment]
I'll add timestamps to that table too...

**Comment by scienceanna** [comment]
Sounds great in terms of output, that's similar to what I've done in the past & has worked well.

We could introduce some sort of weighting for the number of clicks in the fitness function - though I'm not sure it's necessarily totally obvious which is the "better" strategy. Possibly in nature it's better to wait and make one attempt - but this game is obviously going to be somewhat artificial and unless we explicitly instruct participants to try to make as few attempts as possible it seems unfair to penalise for a strategy that might be just as effective in the context of a touch screen computer game!

**Comment by nebogeo** [comment]
We could make the target run away from the mouse if you miss it in a bodged attempt?

**Comment by nebogeo** [comment]
This is now done (the 'performance' table) we can potentially use this later on to judge player skill too... I'll move the 'run away' note above to a new ticket.
