### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by scienceanna** [nebogeo/seeme#7]
We will provide you with some backgrounds (hopefully towards the end of next week), we were thinking of using about 40 different backgrounds that will be used randomly, if that sounds sensible.

**Comment by nebogeo** [comment]
yes, perfect. also you can group them for comparison too

**Comment by lauraakelley** [comment]
Sorry Anna and I have been slow on this, we'll try to provide some backgrounds in the next few days!

**Comment by nebogeo** [comment]
These are in now - kept them as pngs but the makes them quite slow to load, is it ok to use jpgs, or are you avoiding compression artefacts?

**Comment by scienceanna** [comment]
Roughly how much slower to load is it? Seems to be okay on my PC/internet connection but I guess it might be more of an issue on other set ups.

**Comment by nebogeo** [comment]
They are about double the size, so lets see - they load in the background while the players are navigating the menus, so it might be ok.
