### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by scienceanna** [nebogeo/seeme#8]
We thought it might be fun to have some cartoonish 'splat' sounds whenever a target is caught - do you have any that could be used?

**Comment by nebogeo** [comment]
sure, it could do with a lot more work in this area actually - as presumably it's one thing that won't affect the perception?

**Comment by lauraakelley** [comment]
Yes, sounds should be fine.

**Comment by nebogeo** [comment]
Ok, I've added some ridiculous sound effects - just testing the idea really, if it works I'll add some more refined ones! :D

**Comment by scienceanna** [comment]
I think the sounds are awesome, they crack me up. If more work is to be done, can they be made even more ridiculous? :D

**Comment by nebogeo** [comment]
Lots more silliness added...
